# Generated by Django 5.0.3 on 2024-09-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Not Ordered', 'Not Ordered'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('shipped', 'Shipped'), ('Completed', 'Completed'), ('Refunded', 'Refunded')], default='Not Ordered', max_length=20),
        ),
    ]
