# Generated by Django 5.0.3 on 2024-03-17 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='product/image', verbose_name='image')),
                ('price', models.IntegerField(verbose_name='price')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Pending Review', 'Pending Review'), ('Draft', 'Draft')], default='Pending Review', max_length=50, verbose_name='status')),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Password protected', 'Password protected'), ('Private', 'Private')], default='Public', max_length=50, verbose_name='visibility')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
