# Generated by Django 4.2.11 on 2024-04-07 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='slug')),
            ],
            options={
                'verbose_name': 'Attribute',
                'verbose_name_plural': 'Attributes',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', models.SlugField(null=True)),
                ('image', models.ImageField(upload_to='category/image', verbose_name='image')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='product/image', verbose_name='image')),
                ('price', models.IntegerField(verbose_name='price')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('slug', models.SlugField(allow_unicode=True, max_length=250, unique=True, verbose_name='slug')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Pending Review', 'Pending Review'), ('Draft', 'Draft')], default='Pending Review', max_length=50, verbose_name='status')),
                ('product_type', models.CharField(choices=[('Simple', 'Simple'), ('Variable', 'Variable')], default='Simple', max_length=50, verbose_name='product type')),
                ('visibility', models.CharField(choices=[('Public', 'Public'), ('Password protected', 'Password protected'), ('Private', 'Private')], default='Public', max_length=50, verbose_name='visibility')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ManyToManyField(related_name='products', to='product.category', verbose_name='categories')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('value', models.CharField(max_length=200)),
                ('attribute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute', to='product.attribute', verbose_name='attribute')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_attribute', to='product.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField(default=1, verbose_name='quantity')),
                ('price', models.IntegerField(default=0, verbose_name='price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variation', to='product.product', verbose_name='product')),
                ('product_attribute', models.ManyToManyField(related_name='product_attribute', to='product.productattribute', verbose_name='product attribute')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
            },
        ),
    ]
